name: Discussions Notification
on:
  discussion:
    types: created
  discussion_comment:
    types: created
    
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
         channel-id: 'C022NLSRAJU'  # Slack channel id to post message
         slack-message: 'posting from a github action!'
        env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
