name: Discussions Notification
on:
  discussion:
    types: created
  discussion_comment:
    types: created
    
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
         channel-id: 'C022NLSRAJU'  # Slack channel id to post message
         slack-message: 'There is a new ${{ github.event_name }} in the Battlesnake Feedback Repo! Check it out now at https://play.battlesnake.com/feedback'
        env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
